      services:
        backend: 
              build:
               context: .
              
               dockerfile: Dockerfile
              command:  'python app.py'
              ports:
                - '8001:5000'
              volumes:
                - .:/FlaskAPP
              depends_on: 
                - db  


        queue:
            build:
               context: .
               dockerfile: Dockerfile
            restart: always   
            command:  'python consumer.py'
            
            depends_on: 
                - db
                
        db:
            image: postgres:10.18
            restart: always
            environment:
              POSTGRES_DATABASE: main
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: 1234
            ports:
              -  '5433:5432'  
           
     
        # db:
        #     image: mysql:8.0.28
        #     restart: always
        #     environment:
        #       MYSQL_DATABASE: main
        #       MYSQL_ROOT_USER: root
        #       MYSQL_USER: root
        #       MYSQL_PASSWORD: root
        #       MYSQL_ROOT_PASSWORD: sql@1234
        #     volumes:
        #         - .dbdata:/var/lib/mysql
        #     ports:
        #        - '33067:3306'

